# Numpy Demo

## Basics

Numpy is multi dimentional array package.

In [39]:
import numpy as np

np.array() gets a python list ov numbers ang returns numpy array (ndarray)

In [40]:
a = np.array([1,2,3])

In [41]:
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [42]:
b = np.array([[1,2,3],[4,5,6]])#2 dimensional
print(b)

[[1 2 3]
 [4 5 6]]


### Attributes

In [43]:
#get dimention
print(a.ndim)
#get shape
print(b.shape)
#get type
print(a.dtype)
#get item size(bytes)
print(b.itemsize)
#total size
print(a.nbytes)

1
(2, 3)
int32
4
12


In [44]:
c = np.array([1,2,23],dtype='int16')
print(c.dtype)
print(c.itemsize)

int16
2


## Channge elements (rows, columns)

In [45]:
d = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(d)
print(d.shape)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
(2, 6)


In [46]:
#to get elem. write array[r,c]
d[0,3]

4

In [47]:
#to get row write array[r] (or [r,] ( or [r, :]))
d[1]

array([1, 2, 3, 4, 5, 6])

In [48]:
#[:,c] for columns
d[:,3]

array([4, 4])

In [49]:
# [start,end,step]
d[0, 2:-1:2]

array([3, 5])

In [50]:
d[1,3] = 999
d

array([[  1,   2,   3,   4,   5,   6],
       [  1,   2,   3, 999,   5,   6]])

In [51]:
d[0,1::2] = -1
d

array([[  1,  -1,   3,  -1,   5,  -1],
       [  1,   2,   3, 999,   5,   6]])

In [53]:
tri_de = np.array([[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]])
tri_de

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [55]:
tri_de[0,1,1]

2

In [56]:
tri_de[0,:,:]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [57]:
tri_de[0:1,1:,:1]

array([[[1],
        [1]]])

In [169]:
print(a)
print()
print(a[[0,2]])
print()
print(a[[True,False,True]])

[[ 1  2  3  0]
 [ 4  5  6  1]
 [ 7  8  9 10]]

[[ 1  2  3  0]
 [ 7  8  9 10]]

[[ 1  2  3  0]
 [ 7  8  9 10]]


## Iinitializing

In [58]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [59]:
np.ones((3,3,3),dtype = 'int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [60]:
np.full((3,4),-75)

array([[-75, -75, -75, -75],
       [-75, -75, -75, -75],
       [-75, -75, -75, -75]])

In [74]:
erkusy_ireqi_vra = np.ones((2,3))
print(np.full(erkusy_ireqi_vra.shape,-11))
print(np.full_like(erkusy_ireqi_vra,-11))#aranc .shape

[[-11 -11 -11]
 [-11 -11 -11]]
[[-11. -11. -11.]
 [-11. -11. -11.]]


In [75]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

## RANDOM

In [63]:
np.random.rand(2,3)

array([[0.03388683, 0.59113421, 0.96959549],
       [0.44521939, 0.12938687, 0.19958956]])

In [66]:
np.random.random_sample(erkusy_ireqi_vra.shape)

array([[0.81321033, 0.47723813, 0.63429518],
       [0.34811445, 0.8979178 , 0.24758204]])

In [67]:
#integers
np.random.randint(7)

6

In [69]:
np.random.randint(-10,10,size=(3,3))

array([[  9,   5,   9],
       [  0, -10,  -6],
       [  4,  -7,   8]])

## More functions

In [76]:
a = np.array([1,2,3])
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [78]:
a = np.array([[1,2,3]])
np.repeat(a,3,axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [79]:
np.repeat(a,3,axis=1)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [80]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z

output

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Be carefull when copying arrays

In [83]:
a = np.array([1,2,3])
b = a
b[0] = -1000
a

array([-1000,     2,     3])

In [84]:
a = np.array([1,2,3])
b = a.copy()
b[0]=-1000
a

array([1, 2, 3])

## Mathemathics

In [85]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [86]:
a+2

array([3, 4, 5])

In [88]:
a*10

array([10, 20, 30])

In [89]:
a/10

array([0.1, 0.2, 0.3])

In [90]:
a**2

array([1, 4, 9], dtype=int32)

In [95]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [97]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [98]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [91]:
b = np.array([1,0,1])
b

array([1, 0, 1])

In [92]:
a+b

array([2, 2, 4])

In [93]:
a*b

array([1, 0, 3])

In [94]:
a/b

C:\Users\Varuzhan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ 1., inf,  3.])

## Linear Algebra

In [101]:
a = np.full((2,3),3)
b = np.full((3,2),-1)
np.matmul(a,b)#matrix multipilication

array([[-9, -9],
       [-9, -9]])

In [113]:
a = np.array([[2,-1,0],
              [-1,2,-1],
              [0,-1,2]])
a

array([[ 2, -1,  0],
       [-1,  2, -1],
       [ 0, -1,  2]])

In [130]:
print('det(a) =  ',np.linalg.det(a))
print('norm(a) =  ',np.linalg.norm(a))
print('trace(a) =  ',np.trace(a))
print('inverce of a =  \n',np.linalg.inv(a))
print('\ncolesky decomposition =  \n',np.linalg.cholesky(a))
print('\nSingular Value Decomposition')
u,s,vt = np.linalg.svd(a)
print('U = ',u)
print('S = ',s)
print('V^T = ',vt)

print('\neigenvalues = ',np.linalg.eigvals(a))

det(a) =   4.0
norm(a) =   4.0
trace(a) =   6
inverce of a =  
 [[0.75 0.5  0.25]
 [0.5  1.   0.5 ]
 [0.25 0.5  0.75]]

colesky decomposition =  
 [[ 1.41421356  0.          0.        ]
 [-0.70710678  1.22474487  0.        ]
 [ 0.         -0.81649658  1.15470054]]

Singular Value Decomposition
U =  [[-5.00000000e-01 -7.07106781e-01  5.00000000e-01]
 [ 7.07106781e-01 -3.32148455e-16  7.07106781e-01]
 [-5.00000000e-01  7.07106781e-01  5.00000000e-01]]
S =  [3.41421356 2.         0.58578644]
V^T =  [[-5.00000000e-01  7.07106781e-01 -5.00000000e-01]
 [-7.07106781e-01  2.24174877e-16  7.07106781e-01]
 [ 5.00000000e-01  7.07106781e-01  5.00000000e-01]]

eigenvalues =  [3.41421356 2.         0.58578644]


## Statistics

In [131]:
stats = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
stats

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [132]:
np.min(stats)

1

In [133]:
np.max(stats, axis =0)

array([7, 8, 9])

In [134]:
np.max(stats, axis =1)

array([3, 6, 9])

In [135]:
np.sum(stats)

45

In [138]:
np.sum(stats, axis = 0)#sum of columns

array([12, 15, 18])

## Reorganizing

In [142]:
a = np.array([[1,2,3,0],
             [4,5,6,1],
             [7,8,9,10]])
a

array([[ 1,  2,  3,  0],
       [ 4,  5,  6,  1],
       [ 7,  8,  9, 10]])

In [143]:
a.reshape((2,6))

array([[ 1,  2,  3,  0,  4,  5],
       [ 6,  1,  7,  8,  9, 10]])

In [146]:
a.reshape((1,12))

array([[ 1,  2,  3,  0,  4,  5,  6,  1,  7,  8,  9, 10]])

In [147]:
a.reshape((2,2,3))

array([[[ 1,  2,  3],
        [ 0,  4,  5]],

       [[ 6,  1,  7],
        [ 8,  9, 10]]])

In [149]:
#Vertical stacking
v1 = np.array([1,2,3,4])
v2 = np.array([1,2,3,4])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [150]:
#horizontal stacking
h1 = np.array([1,2,3,4])
h2 = np.array([1,2,3,4])
np.hstack([h1,h2])

array([1, 2, 3, 4, 1, 2, 3, 4])

## Reading data from files

In [154]:
txt = '''
11,12,13,14,15,16
21,22,23,24,25,26
31,32,33,34,35,36
'''
with open('data.txt','w') as f:#writing text to .txt file
    f.write(txt)

filedata = np.genfromtxt('data.txt',delimiter=',')#generating matrix
filedata

array([[11., 12., 13., 14., 15., 16.],
       [21., 22., 23., 24., 25., 26.],
       [31., 32., 33., 34., 35., 36.]])

## Boolean masking and Advenced indexing

In [155]:
filedata>24

array([[False, False, False, False, False, False],
       [False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [173]:
np.any(filedata>24)

True

In [174]:
np.any(filedata>24,axis = 1)

array([False,  True,  True])

In [175]:
np.all(filedata>24,axis = 1)

array([False, False,  True])

In [156]:
filedata[True]

array([[[11., 12., 13., 14., 15., 16.],
        [21., 22., 23., 24., 25., 26.],
        [31., 32., 33., 34., 35., 36.]]])

In [157]:
filedata[False]

array([], shape=(0, 3, 6), dtype=float64)

In [158]:
filedata[filedata>24]

array([25., 26., 31., 32., 33., 34., 35., 36.])

In [180]:
(filedata>24) & (filedata<32)

array([[False, False, False, False, False, False],
       [False, False, False, False,  True,  True],
       [ True, False, False, False, False, False]])

In [187]:
!("img/indexing.png")

# Cool Youtube Videos
### Numpy Tutorial: https://www.youtube.com/watch?v=GB9ByFAIAH4
### Creating Game with Numpy!" https://www.youtube.com/watch?v=UYgyRArKDEs
### Data vizualization with matplotlib and numpy: https://www.youtube.com/watch?v=DAQNHzOcO5A

# Links with more information! 

NumPy vs Lists:https://jakevdp.github.io/blog/2014/05/09/why-python-is-slow/

Indexing: https://docs.scipy.org/doc/numpy-1.13.0/user/basics.indexing.html

Array Creation Routines:https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html

Math Routines Docs:https://docs.scipy.org/doc/numpy/reference/routines.math.html

Linear Algebra Docs:https://docs.scipy.org/doc/numpy/reference/routines.linalg.html